### ISSUE TITLE
Error: Value 'i1808' is not an integer

### ISSUE THREAD

**Issue by soerensen3** [wrightmat/zbom#71] opened 2016-12-11 19:29 UTC
Hello!

I constantly get "Error: Value 'i1808' is not an integer" during playing (linux 64bit fedora) using version 1.5.1 of solarus and latest release zbom. However it would not crash the game on solarus 1.5.1 so it's only in the background.

[savegame.zip](https://github.com/wrightmat/zbom/files/644711/savegame.zip)

**Comment by wrightmat** [comment] 2016-12-17 16:19
I believe this has already been fixed and will be included in the next version, but can you attach the error.txt file as well so I can confirm? Thanks!

**Comment by soerensen3** [comment] 2016-12-19 23:05
Sure...
[error.txt](https://github.com/wrightmat/zbom/files/662379/error.txt)

**Comment by wrightmat** [comment] 2016-12-20 19:54
Great. No script identifier or line number... Logged issue #1010 with the Solarus engine: https://github.com/solarus-games/solarus/issues/1010

**Comment by christopho** [comment] 2016-12-20 20:11
@wrightmat what is the i1808 value used for?

**Comment by wrightmat** [comment] 2016-12-21 03:30
Possession variable for one of my items, the boomerang, which has two variants. It actually is an integer, as far as I know.

**Comment by christopho** [comment] 2016-12-21 16:21
I think I know what happens.
i1808 is the possession state of the boomerang (an integer), but it was also (wrongly) used as the savegame variable of a chest on map 201. So there was a conflict (same variable name used twice). Savegame variables of chests are booleans, which explains the error message.

You fixed it in commit https://github.com/wrightmat/zbom/commit/6847738d6f2ebb63ac63073e0bd9aca5a90e0cda, but people who played before this commit can have an existing savegame with the problem.

A solution can be to check the type of game:get_value("i1808") whenever a game starts, and to fix it if it is a boolean. Don't worry, in ZSDX, I also have some code to fix broken savegames due to a previous bug: https://github.com/solarus-games/zsdx/blob/dev/data/play_game.lua#L68

On the engine side, I am not sure if there is something to fix.

**Comment by wrightmat** [comment] 2016-12-21 16:24
Ah, I guess I just wasn't aware there was a change to the chests. Guess that takes care of that - thanks!

**Comment by christopho** [comment] 2016-12-21 16:25
It is related to the change that makes chests more customizable (on_empty() -> on_opened()): http://wiki.solarus-games.org/doku.php?id=upgrade_from_1.4_to_1.5#more_customizable_chests

**Closed** 2016-12-28 02:17 UTC
